logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8080
spring:
  security:
    user:
      name: root
      password: root
      roles:
        - admin
        - guest
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#     第一次用 ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
app:
  security:
    enableCrsf: false
    permitUrl:  /**,/login,/user/**
    formLoginUrl: /login
    tokenHeader: Authorization
#    设置一小时后过期
    jwtExpireAt: 3600
